### ISSUE TITLE
Src is not working when use and url

### ISSUE THREAD

**Issue by jholbert1** [xiaxiangfeng/react-3d-model#1]
Hello i have this problem, when i use an external url from my backend i have blocked by cors

example
<Model.GLTF src="https://my-domain-url/pepsi_can.glb" />

error message: 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

thanks for your help

**Comment by xiaxiangfeng** [comment]
I used an address of a third party and found no error. I guess it may be your address set a limit

<Model.GLTF src="https://threejs.org/examples/models/gltf/collision-world.glb" />

**Comment by sebpo-dev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

shcallaway, @maomao321, @GuoyiZhang, @yakun0622, @anggxyz, @ted2810, @Tonaky, @MA-Ahmad, @chenz85, @yunstv, @perx666, @olivierloverde, @vasuharish, @aligos, @weiliu955, @Cansiny0320, @ali5152, @TimDaub, @hexablob, @djosey
